
# Iniciando um Banco de dados MongoDB em um container Docker

version: '3'

services:
  conversao-temperatura:
    image: alexsandrolechner/conversao-temperatura:${TAG}
    ports:
    - 8080:8080
    container_name: 'conversao-temperatura'
    restart: always # iniciar com o servidor


  conversao-distancia:
    image: alexsandrolechner/conversao-distancia:${TAG}
    ports:
    - 5000:5000
    container_name: 'conversao-distancia'
    restart: always # iniciar com o servidor

  conversao-peso:
    image: alexsandrolechner/conversao-peso:${TAG}
    ports:
    - 8081:80
    container_name: 'conversao-peso'
    restart: always # iniciar com o servidor